### ISSUE TITLE
Tracking only 1 group

### ISSUE THREAD

**Issue by Shaomk** [Hipjea/studentstracker#1]
Hello, please tracking only 1 group to choose from all.
Thanks

**Comment by Hipjea** [comment]
Hello, thanks for this good idea.
It's done in last commit [https://github.com/Hipjea/studentstracker/commit/84f0c85bf3bc67cd539f0cc797ba0fe266459013](https://github.com/Hipjea/studentstracker/commit/84f0c85bf3bc67cd539f0cc797ba0fe266459013)

**Comment by Hipjea** [comment]
Hi, thanks for the good idea. 
It's done in the last commit https://github.com/Hipjea/studentstracker/commit/84f0c85bf3bc67cd539f0cc797ba0fe266459013
