### ISSUE TITLE
Proposed modifications from a teacher

### ISSUE THREAD

**Issue by aceduder** [Hipjea/studentstracker#10]
I installed the Student Tracker and got this feedback from one of my instructors:

This is helpful.  Is it possible to make two changes, first the dates, can they be put in MM/DD/YYYY (U.S.) format?  Second, is it possible to sort the order by most recent date accessed rather than in alphabetical order by last name?  Oh, it would be good if the student's email could be included.  That way I could just copy the email address or maybe click to email them right from the Student Tracker tool!
 
If these changes can be made, I'd like to see this feature added to all my courses.
 
Continuing thinking, those who have not accessed the course for say 50 days could be put in a separate group at the bottom as they are likely really gone.

**Comment by Hipjea** [comment]
Thank you for these relevant proposals. They are all implemented in the [1.7 release](https://github.com/Hipjea/studentstracker/releases/tag/1.7.0)
