### ISSUE TITLE
Version 1.7.0 (2021022601) layout problems

### ISSUE THREAD

**Issue by Richardvi** [Hipjea/studentstracker#19]
Thanks for your block, really nice. We have been using it for quite some while.

However, the latest update really messes with the block layout. On a full HD screen it still shows like this:
![image](https://user-images.githubusercontent.com/5486910/109792644-04674900-7c14-11eb-909c-a66cddc2e226.png)

Any idea in how to fix this?

**Comment by Hipjea** [comment]
Thanks for your feedback ! This commit should fix the problem [https://github.com/Hipjea/studentstracker/commit/0598dbc3db0abfa830422a997b7b5d9dc3465fc1](https://github.com/Hipjea/studentstracker/commit/0598dbc3db0abfa830422a997b7b5d9dc3465fc1).

I'm pushing a new release with the fix in the Moodle repository.

**Comment by Hipjea** [comment]
Thanks for your feedback ! This commit should fix the problem [https://github.com/Hipjea/studentstracker/commit/0598dbc3db0abfa830422a997b7b5d9dc3465fc1](https://github.com/Hipjea/studentstracker/commit/0598dbc3db0abfa830422a997b7b5d9dc3465fc1).

I'm pushing a new release with the fix in the Moodle repository.

**Comment by Richardvi** [comment]
Has the new version been pushed? I can't see it yet...

**Comment by Hipjea** [comment]
@Richardvi yes, it's embedded in the 1.7.1 release on the official repository h[ttps://moodle.org/plugins/pluginversion.php?id=23597](https://moodle.org/plugins/pluginversion.php?id=23597)

**Comment by Richardvi** [comment]
That is weird. It's nog being pushed from moodle.org as an update. I have this version, just ran a 'check for updates' on the plugin page - but student tracker is not popping up. Do you perhaps have a wrong date or version number somewhere?
![image](https://user-images.githubusercontent.com/5486910/111498706-75454f80-8742-11eb-8245-d472fcaf23c4.png)

I will manually install this update then...

**Comment by Richardvi** [comment]
I can confirm: something is definitely wrong with the version numbers. I manually downloaded the latest version, but it won't install. It thinks I have a newer version (or the same version) already installed.

**Comment by Richardvi** [comment]
If you download the latest version from moodle.org, you still get this version.php:

defined('MOODLE_INTERNAL') || die();

$plugin->version   = 2021022601;
$plugin->requires  = 2016052300;
$plugin->release  = '1.6.2';
$plugin->component = 'block_studentstracker';
$plugin->maturity = MATURITY_STABLE;

**Comment by Hipjea** [comment]
I believe that you already have the same version of the plugin. You can check under Moodle administration /admin/plugins.php

**Comment by Hipjea** [comment]
I don't know if you are able to check the plugin files on your server, but you could inspect the `styles.css` file in order to know if it has the CSS fix [https://github.com/Hipjea/studentstracker/commit/0598dbc3db0abfa830422a997b7b5d9dc3465fc1](https://github.com/Hipjea/studentstracker/commit/0598dbc3db0abfa830422a997b7b5d9dc3465fc1)

**Comment by Richardvi** [comment]
I can't get it to work. I've cut and paste this code: https://github.com/Hipjea/studentstracker/blob/main/styles.css into my styles.css on the student tracker. No changes at all.

**Comment by Hipjea** [comment]
You have to rebuild your theme's CSS cache through the cli : `php admin/cli/build_theme_css.php` (see [https://docs.moodle.org/310/en/Administration_via_command_line#Build_theme_CSS_cache](https://docs.moodle.org/310/en/Administration_via_command_line#Build_theme_CSS_cache))
Or by turning on and off the theme Designer Mode in Moodle's admin.

**Comment by Richardvi** [comment]
I have already done this. Makes no difference. I'm still pretty sure your download-links are not correct.

**Comment by Hipjea** [comment]
@Richardvi the zip I download from the official repository contains the CSS fix actually. Your issue could come from the theme of your platform, as this CSS relies on Bootstrap.
I'll try to add a fix including the float utilities directly in the plugin's stylesheet.

**Comment by Richardvi** [comment]
That might be it then 👍 I use Fordson, based upon Boost
