### ISSUE TITLE
Can not translate some language strings 

### ISSUE THREAD

**Issue by caiado** [Hipjea/studentstracker#2]
Hi,

On block config page I can not translate the following:

- **Block title** (_blocktitle_)
- **Text when no access at all** (_block_studentstracker_text_never_)

Ricardo

![translate](https://cloud.githubusercontent.com/assets/533328/20063119/2988aa4c-a4ed-11e6-93cf-23ab0440a0a5.png)

**Comment by Hipjea** [comment]
Hi @caiado 
Can you make a pull request, so I could try your translation ?

**Comment by caiado** [comment]
ok, but how it is done? Newbie here...

**Comment by Hipjea** [comment]
I dunno if you already use a terminal and if you're able to run git commands...

- You have to fork my repository --> https://github.com/Hipjea/studentstracker - Fork button
- then, you just clone your new forked repository : `git clone https://github.com/caiado/studentstracker`
- modify or create the translation file inside the local copy : 
- push the modifications to your Github repo : `git add .` `git commit -m "translation"` `git push origin master`
- then you can create a new Pull Request : [https://github.com/Hipjea/studentstracker/pulls](url)

There's a guide there [https://help.github.com/articles/fork-a-repo/](url).
If it's not possible, you could also paste your translation file here, but you'd maybe like to contribute to this plugin :)

**Comment by caiado** [comment]
ok, but all the translations were done via Moodle, not GitHub.

**Comment by Hipjea** [comment]
It's as you wish, but it's a case to contribute if you want to.
As I wrote, you can also just paste it here so I can add it myself.

**Comment by caiado** [comment]
I translated all strings via Moodle, but these 2 are not showing the correct translation. It seems it is hard coded, I think.

**Comment by Hipjea** [comment]
Ok no problem. Can you just paste the full translations here ? I'll add them in a new version.

**Comment by caiado** [comment]
Sure...

(1) Block title = Título do bloco
(2) Text when no access at all = Texto para quando não tiver acesso

**Comment by Hipjea** [comment]
Thanks ! Is that portuguese ?

**Comment by caiado** [comment]
Correct.

It is Brazilian Portuguese

**Comment by Hipjea** [comment]
Ok great !
Can you tell me if this translation is okay for you ?

[https://github.com/Hipjea/studentstracker/blob/master/lang/pt/block_studentstracker.php](https://github.com/Hipjea/studentstracker/blob/master/lang/pt/block_studentstracker.php)

**Comment by caiado** [comment]
Some corrections:

$string['days_critical'] = 'Limite crítico (em dias)';
$string['color_days'] = 'Cor dos dias';
$string['color_days_critical'] = 'Cor dos dias críticos';
$string['color_never'] = 'Cor para nenhum acesso';
$string['header_fine'] = 'Texto para quando estiver tudo bem';
$string['text_footer'] = 'Clique no nome para contatá-los';
$string['role'] = 'Rastrear todos os papéis ?';
$string['roles'] = 'Papéis permitidos para ver o bloco';
$string['groups'] = 'Grupos a monitorar';
$string['truncate'] = 'Apenas mostrar n resultados';

That´s it!!!
