### ISSUE TITLE
Can not update latest version (09  Nov) via web

### ISSUE THREAD

**Issue by caiado** [Hipjea/studentstracker#3]
Can not update from 2016110900 to 2016110901 via web.

**Comment by Hipjea** [comment]
Hi,
It's probably the same issue due to .git folder.
Can you try with the fresh 2016110903 version ?

**Comment by caiado** [comment]
I'm trying to upgrade from "2016110900" to "2016110903", but it says the new version is "20150511" (???) and says it can not "downgrade"...

See images...
![screenshot from 2016-11-09 14-05-20](https://cloud.githubusercontent.com/assets/533328/20145089/e257b128-a685-11e6-92c6-1a4970f849d0.png)
![screenshot from 2016-11-09 14-05-54](https://cloud.githubusercontent.com/assets/533328/20145097/e9bd03a0-a685-11e6-9f1b-d2a5045d5d01.png)

**Comment by caiado** [comment]
Your "version.php" is wrong...

"$plugin->version   = 2015051100;"

**Comment by Hipjea** [comment]
Ok, my bad, I made a typo when I added a version for Moodle 3.2 !
It should be fixed with this new version 2016110905 https://moodle.org/plugins/pluginversion.php?id=12556

**Comment by caiado** [comment]
It worked!!!

**Comment by Hipjea** [comment]
Thanks for your patience, I'll try to avoid those errors in the near future ;)

**Comment by caiado** [comment]
No harm done!!
