### ISSUE TITLE
Minor typos in English language strings

### ISSUE THREAD

**Issue by germanvaleroelizondo** [Hipjea/studentstracker#4]
Hi,
When I was translating into Mexican Spanish your studentstracker plugin in AMOS, I found a couple of odd-looking English language strings:

roles | block_studentstracker 'Roles allowed to see toe block'
I think that it should be 'Roles allowed to see the block'

I am not sure if text_footer | block_studentstracker 'Contact incitation message' should really be 'invitation' instead of 'incitation'.

Thanks in advance for your help.

**Comment by Hipjea** [comment]
Hi @germanvaleroelizondo and thanks for your help !
I will fix it right now. 
The text_footer string is actually intented to motivate teachers to send messages to the students listed in the block. So I guess you're right about invitation !

**Comment by germanvaleroelizondo** [comment]
Thanks a lot.

**Comment by Hipjea** [comment]
I've corrected the typos in https://github.com/Hipjea/studentstracker/commit/67d2631d7c7618bc2950ab46fb966e3499d66723
